---
# These variables override those defined by roles

# App variables - apply to a single project
app_project: "icehack"
app_project_repository: "https://github.com/antarctica/icehack"
app_project_directory: "/srv/apps/{{ app_project }}"

# BAS Systems Inventory variables
bas_systems_inventory_system_reference: "{{ app_project }}"
